### ISSUE TITLE
Update site not reachable ...

### ISSUE THREAD

**Issue by konfri** [java-decompiler/jd-eclipse#17]
Hey,

I tried to install the eclipse plugin via the update site mentioned here http://jd.benow.ca/#jd-gui-download

![update_site](https://cloud.githubusercontent.com/assets/16843990/23377284/ba562316-fd2f-11e6-9449-c4dd3bcb3fc5.png)

Apparently, it is down. 

An other opportunity would to upload the eclipse repository to github? :)

Best regards,

Kon

**Comment by xanaxan** [comment]
http://jd.benow.ca/jd-eclipse/update/

**Comment by konfri** [comment]
Thanks for your reply, this one works :)
