### ISSUE TITLE
Cannot install JD-Eclipse on PortableApps platform

### ISSUE THREAD

**Issue by cstarr11** [java-decompiler/jd-eclipse#28]
I'd like very much to use the JD-eclipse plugin for Eclipse on my 1TB portable drive (using Eclipse OXYGEN 4.7.3 Platform Runtime Binary [Portable].paf.exe), but install attempts so far have failed. I used the same zip file as I used for the Windows Eclipse (Oxygen) install (jd-eclipse-site-1.0.0-RC2.zip), and the install to the portable drive failed. Attached is a file with the output describing the issue. I hope this is not a bone-head lapse on my part.

Thanks very much,
CJS
[JD-Eclipse Decompiler (portable) dependency details.txt](https://github.com/java-decompiler/jd-eclipse/files/1843404/JD-Eclipse.Decompiler.portable.dependency.details.txt)

**Comment by emmanue1** [comment]
I just installed JD-Eclipse on Eclipse 4.10 in portable mode:
![image](https://user-images.githubusercontent.com/11559196/61234613-cc0bb200-a733-11e9-8d9a-b38cc5d16a6e.png)
I'll release the version in few days.
