### ISSUE TITLE
Compatibility with Eclipse 4.10 (2018-12)

### ISSUE THREAD

**Issue by LucioMenci** [java-decompiler/jd-eclipse#29]
Hi,

I used jd-eclipse for years in all versions from 4.2 to 4.9, but when I installed it into the 4.10 I cannot see Preverence -> Java -> Decompiler, and it doesn't decompile .class files. If I try to reinstall, eclipse says that it is already installed. There are some incompatibility?

![snap1](https://user-images.githubusercontent.com/15246491/50693103-47c6cc80-1036-11e9-8dc0-d09899a585ee.jpg)
![snap2](https://user-images.githubusercontent.com/15246491/50693107-4b5a5380-1036-11e9-8e7e-4992ec20939e.jpg)

Thankyou
Lucio

**Comment by felipebraga** [comment]
It seems JD Eclipse doesn't work anymore. 😞

**Comment by actionableanalytics** [comment]
I am using Eclipse 4.9.0 and it also shows up in Windows > Preferences > Java > Decompiler and also in Help > About > Java Decompiler (Steaming Hot Cup Icon) but still it does not de compiles any class file. As a workaround I am using JD-GUI but not able to debug class files now. Any pointers in this regard will be greatly appreciated.

![image](https://user-images.githubusercontent.com/7386853/53358195-a5500900-3955-11e9-9825-7836a495f471.png)

**Comment by kmarx** [comment]
Same here. 
Version: 2018-12 (4.10.0)
Build id: 20181214-0600
As a work-around, I used JD-GUI to save all source as a source jar and attached that as the source in Eclipse. It seems to _mostly_ work, but still doesn't allow eclipse to see some source, even though I can clearly see it both in JD-GUI and via jar xf <x.source.jar.zip>.

**Comment by emmanue1** [comment]
Project updated. JD-Eclipse 2.0.0 works under Eclipse 4.10.
![image](https://user-images.githubusercontent.com/11559196/61234319-0e80bf00-a733-11e9-941e-4f68b2e6dfd2.png)
I'll release the version in few days.
