### ISSUE TITLE
Windows uppercase extension ignored

### ISSUE THREAD

**Issue by cetebuk** [java-decompiler/jd-eclipse#30]
OS: Windows
Tested versions: 1.4.3, 1.5.0 

If jar file has it's extension in uppercase (like: joo.JAR or FOO.JAR) file can not be opened.

**Comment by emmanue1** [comment]
Hi, could you give me more information ? I've create a Eclipse project with a .jar and .JAR files. Everything seems ok.
![image](https://user-images.githubusercontent.com/11559196/61181125-fc632b80-a621-11e9-92eb-aa60092eefab.png)

**Comment by cetebuk** [comment]
OS Win 7 Pro 64-bit (with all latest updates). 
Java JDK 8 Update 201 (64-bit).

Java Decompiler  (see image "version")
JD-GUI ver 1.5.0
JD-Core ver 1.0.1
![version](https://user-images.githubusercontent.com/18175156/62279500-16ad4f80-b3ff-11e9-942e-aef6514ffda5.jpg)

1) step 1:
Menu -> Open file... selecting "test.jar". 
"Open" button opens it without an issue.
renaming file to "test.JAR", same
2) step 2:
Menu -> Open file... selecting "test.JAR".  (see image "open wrong file")
![open wrong file](https://user-images.githubusercontent.com/18175156/62279521-22007b00-b3ff-11e9-882f-3b61784dad00.jpg)
"Open" button closes "Open" dialog,
 but nothing on the screen (see image "nothing opened")
![nothing opened](https://user-images.githubusercontent.com/18175156/62279524-23ca3e80-b3ff-11e9-9dc2-d70be538e8ed.jpg)

**Comment by cetebuk** [comment]
Sorry, not sure how it ended up in "jd-eclipse". It was meant for "jd-gui". Moving it there.
