### ISSUE TITLE
Can't set JD Class File Viewer as default on file assoc. .class file ext.

### ISSUE THREAD

**Issue by lazuee** [java-decompiler/jd-eclipse#41]
<h1>ISSUE</h1>
<p>I'm struggling on how to deal with this problem where I can't set JD Class File Viewer as default on file assoc. .class file ext. after I restart Eclipse IDE. But, it can set on .class without source. </p>

<h3>Error:</h3>

> The Class File Viewer cannot handle the given input ('org.eclipse.ui.ide.FileStoreEditorInput').

</span>I need help, i'm using Eclipse IDE Version: 2022-03 (4.23.0) and trying to use jd-eclipse-2.0.0 as a decompiler. If someone knows how to solve this problem or experienced the same issue as mine, please comment something here.</span>

⇓ ⇓ ⇓ ⇓

**Comment by robbinmav** [comment]
I had the same problem with the same version.
Go to the Preferences->General->File Associations
the bottom pane (associated editors) will show two entries for "Class File Viewer"

Click on the add button next to the "Associated editors" pane.
A "Editor Selection" dialog box will appear
Select "JD Class File Viewer" 
The JD Class File Viewer will now appear in the list
Click on JD Class File Viewer to select it
Click on "Default" to make it the default editor
Click on "Apply and Close"
that should work
